### ISSUE TITLE
[feat] Replace Moq with NSubstitute

### ISSUE THREAD

**Issue by ikesnowy** [cnblogs/Architecture#139]
Details: https://github.com/moq/moq/issues/1372

**Comment by Creastoff** [comment]
Albert Monteiro has produced this repository with the required patterns to replace Moq with NSubstitute.
https://github.com/AlbertoMonteiro/moq-to-nsubstitute/tree/main

Bare in mind there are still some patterns missing (some of which have been raised as issues in the repo) so you may have to make adjustments depending on your usage of Moq.

I have also writtten the below tool which leverages these patterns to automatically replace instances of Moq with NSubstitute.

https://github.com/Creastoff/Moqstitute

**Comment by ikesnowy** [comment]
> FYI: https://gist.github.com/Creastoff/280a33caa684db756c7cce91d318b41f

Thanks!
